version: '0.2'

phases:
  install:
    commands:
      - npm i -g aws-cdk@1.1.0
      - cdk --version
  build: 
    commands: 
      - env
      - cd api
      - npm i
      - cd handlers && npm i
      - cd ..
      - npm run build
      - zip -r lambda.zip handlers/
      - HASH=$(md5sum lambda.zip | awk '{print $1}')
      - mv lambda.zip $HASH.zip
      - cdk synth -c s3_deploy_bucket=$S3_LAMBDA_BUCKET -c lambda_hash=$HASH
      - ls
artifacts: 
  secondary-artifacts:
    cfn_templates:
      files:
        - 'api/cdk.out/*'
    lambda_package:
      files:
        - 'api/*.zip'
      discard-paths: yes