version: '0.2'

phases:
  install:
    commands:
      - npm i -g aws-cdk@0.36.2
      - cdk --version
  build: 
    commands: 
      - env
      - cd api
      - npm i
      - HASH=$(md5sum lambda.zip | awk '{print $1}')
      - cdk synth -c s3_deploy_bucket=$S3_LAMBDA_BUCKET lambda_hash=$HASH
      - npm run build
      - zip -r $HASH.zip . -i handlers/*.js
      - ls
artifacts: 
  secondary-artifacts:
    cfn_templates:
      files:
        - 'api/cdk.out/*'
    lambda_package:
      files:
        - 'api/*.zip'
      discard-paths: yes