version: '0.2'

phases:
  install:
    commands:
      - npm i -g aws-cdk
      - cdk --version
  build: 
    commands: 
      - env
      - cd api && cdk synth
      - ls api
artifacts: 
  files:
    - '**/*'