version: '0.2'

phases:
  install:
    commands:
      - npm i -g aws-cdk@0.36.2
      - cdk --version
  build: 
    commands: 
      - env
      - cd api
      - npm i
      - cdk synth -c s3_deploy_bucket=$S3_LAMBDA_BUCKET
      - zip -r lambda.zip . -i api/handlers/*
      - ls
artifacts: 
  files:
    - 'api/cdk.out/*'
  secondary-artifacts:
    lambda-package:
      files:
        - lambda.zip